### ISSUE TITLE
[Proposal]: Fully VueJs and Es6

### ISSUE THREAD

**Issue by percymamedy** [mscraftsman/devcon2017#17]
Peaking around the source code, I couldn't keep noticing that in some part of the website VueJS was used to make some pretty cool stuff...

But this is where it bugs me, why haven't VueJs been used fully to make a true and complete SPA using one of the many templates provided by [vue-cli](https://github.com/vuejs/vue-cli) ?

Here are some advantages I can see with moving to a true SPA VueJs App :

- The code could have been easier to maintain if vendor assets were managed with ```npm``` instead of being commited in the source.
- Use of Resuable components in their own ```.vue``` files would have avoided repetition of templates.
- Faster Page load with Javascript Transpilation using webpack or Bublé.
- Use of Es6 the javascript of the Future is so much nicer to code with and maintain.

Maybe for devcon2018 ?

I would be happy to help.

**Comment by Humeira** [comment]
Yeah I agree with you, I've been using VueJs for a while now.

However it was used only for a little part on this project. @nirvanpagooah was tinkering around with it. 

Maybe in the future if we'll use Vue, then yeah why not..
you're welcome to help 😄

**Comment by nirvanpagooah** [comment]
Hello Percy! Thanks for looking at the codes. Yes,

**Comment by nirvanpagooah** [comment]
Hello Percy! Thanks for inspecting the codes. Yes indeed, Vue.js was used on major segments of the site such as Jobs, Speakers & Sponsors section.

**Why haven't VueJs been used fully to make a true and complete SPA using one of the many templates?**

Simply because this wasn't planned. The site design was done in the first place and someone was expected to do the site on Angular 2 which didn't happened since the learning curve of Angular 2 is enormous (TypeScript & stuff) and initially, the legacy site was based on an obsolete version of AngularJS.

Secondly, I had to find a quick fix to get the site online as sponsors were starting to look at the site. That's the reason why bits and pieces of Vue.js code is scattered over the site. But, nevertheless, it worked perfectly on production! :) And of course, manpower :)

I do know the benefits of using simple file components :) 

Definitely, that's would be awesome to have fully Vue.js SPA site for 2018. By the end of the year, a feasibility study over frameworks that would fit our needs will be done. So far, I have also used Vue.js on various projects which are running on production and I must say, I'm at ease with it.

Once the planning for DevConMru2018 is up, I'll ping you for help. Thanks a lot for your getting into the project 👍

**Comment by percymamedy** [comment]
@nirvanpagooah @Humeira thanks for your responses

I must also add that you guys have done a great job in the amount of time you were allocated. So kudos for that!! :tada: :tada: 

My vote will definitely go to VueJs as a framework to use for the next installment of the Site, the learning curve is definitely not as steep as Angular or React and it's frankly the best JS framework I've worked with: 

- A clear cut documentation
- Easy implementation.
- Back by a huge community.
- And some awesome plugins.

Am always available for contributions on Open source projects, reach out to me if you guys are planning to implement an awesome VueJs SPA for the next devcon site.

Always happy to help.

:+1:
